package com.geospock.pubvote.people

/**
 * @author James
 */
enum class People(val slackHandle: String) {
    STEVE("steve"),
    KAI("kai"),
    JON("jon"),
    DAVID_W("david"),
    JAMES_G("james"),
    BOB("bob"),
    BENITA("benita"),
    DAN("dansilk"),
    XAVI("xavi"),
    SAM("sam"),
    FELIX("felix"),
    HUW("huw"),
    NICOLA("nicola"),
    DOM("dom"),
    DAVID_BINNS("davidbinns"),
    DAVID_MB("David Brown"),
    CHARLES("charles"),
    AIMI("aimi"),
    ALISTAIR("alistair"),
    SAM_2("samc"),
    FELIX_SG("felixsg"),
    TRUC("truc"),
    TOM("Tom Bardsley"),
    ALAN("alan"),
    RICHARD("richard"),
    MELANIE("melanie"),
    ISAAC("isaac"),
    NICK("nick"),
    SIMON("simon"),
    GUNNAR("gunnar"),
    ALLEN("allen"),
    AMARIA("amaria"),
    FIONA("fi"),
    THEODORA("theodora"),
    IAN("ian"),
    CAMERON("cameron"),
    ELEANOR("eléanor"),
    THOMAS("thomas"),
    LORENA("lorena"),
    COLETTE("Collette"),
    BEN("ben"),
    SANGEETHA("sangeetha"),
    FLAVIA("Flavia")
    TOMC("TomC")
}
