package com.geospock.pubvote.people

/**
 * @author James
 */
enum class People(val slackHandle: String, val role: Role = Role.PEOPLE_EARTHLINGS_OTHERS_NICOLA) {
    STEVE("steve", Role.EXECUTIVE_LEADERSHIP_TEAM),
    KAI("kai", Role.ENGINEERING_SENIOR_MANAGEMENT_TEAM),
    JON("jon", Role.ENGINEERING_SENIOR_MANAGEMENT_TEAM),
    DAVID_W("david", Role.ENGINEERING_SENIOR_MANAGEMENT_TEAM),
    JAMES_G("james"),
    BOB("bob"),
    BENITA("benita", Role.EXECUTIVE_LEADERSHIP_TEAM),
    DAN("dans"),
    XAVI("xavi"),
    SAM("sam"),
    FELIX("felix"),
    HUW("huw", Role.EXECUTIVE_LEADERSHIP_TEAM),
    NICOLA("nicola"),
    DOM("dom"),
    DAVID_BI("davidbi"),
    DAVID_MB("DavidBr", Role.COMMERCIAL_SENIOR_MANAGEMENT_TEAM),
    CHARLES("charles"),
    AIMI("aimi"),
    ALISTAIR("alistair"),
    SAM_2("samc"),
    FELIX_SG("felixsg", Role.ENGINEERING_SENIOR_MANAGEMENT_TEAM),
    TRUC("truc"),
    TOM("TomBa"),
    ALAN("alan"),
    RICHARD("richard", Role.EXECUTIVE_LEADERSHIP_TEAM),
    MELANIE("melanie"),
    ISAAC("isaac", Role.COMMERCIAL_SENIOR_MANAGEMENT_TEAM),
    NICK("nick"),
    SIMON("simon", Role.EXECUTIVE_LEADERSHIP_TEAM),
    GUNNAR("gunnar", Role.COMMERCIAL_SENIOR_MANAGEMENT_TEAM),
    ALLEN("allen", Role.EXECUTIVE_LEADERSHIP_TEAM),
    AMARIA("amaria"),
    FIONA("fi"),
    THEODORA("theodora"),
    IAN("ian", Role.EXECUTIVE_LEADERSHIP_TEAM),
    CAMERON("cameron"),
    ELEANOR("eléanor"),
    THOMAS("thomas"),
    LORENA("lorena"),
    COLETTE("Collette", Role.COMMERCIAL_SENIOR_MANAGEMENT_TEAM),
    BEN("ben", Role.COMMERCIAL_SENIOR_MANAGEMENT_TEAM),
    SANGEETHA("sangeetha"),
    FLAVIA("Flavia"),
    CHLOE("Chloe"),
    TOMC("TomCo"),
    SERGEJ("sergej"),
    BEN_N("BenNo"),
    SAYUIRI("sayuri"),
    HUGO("hugo"),
    MALCOLM("malcolm"),
    JAKE("jake"),
    KENTA("kenta"),
    ARREN("arren"),
    MAJDI("majdi"),
    SARAH("sarahh"),
    ISRAEL("israel")
}
